[deps]
CDFDatasets = "075ae62b-f872-4368-b383-31e3aa6c3154"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"

[sources]
CDFDatasets = {path = ".."}
