name = "CDFDatasets"
uuid = "075ae62b-f872-4368-b383-31e3aa6c3154"
version = "0.1.5"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]

[deps]
CommonDataFormat = "a9737db6-c05c-4e48-868b-6bc41491d9d9"
CommonDataModel = "1fbeeb36-5f17-413c-809b-666fb144f157"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"

[weakdeps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
PyCDFpp = "8480bde4-bc3c-44e7-baab-4ff1aa53fe88"
SpacePhysicsMakie = "0c28ffd8-ae30-4a56-b2e4-f8332c621ad2"

[extensions]
CDFDatasetsDimensionalDataExt = "DimensionalData"
CDFDatasetsPyCDFppExt = "PyCDFpp"
CDFDatasetsSpacePhysicsMakieExt = "SpacePhysicsMakie"

[compat]
CommonDataFormat = "0.1.2"
CommonDataModel = "0.4"
Dates = "1"
DimensionalData = "0.29"
DiskArrays = "0.4"
PyCDFpp = "0.1"
SpacePhysicsMakie = "0.1, 0.2"
julia = "1.10"
